In [35]:
import numpy as np

# 1)Converting list to Array

In [36]:
lst=[1,2,3,4]
print(type(lst))
arr=np.array(lst)
print(type(arr))
print(arr)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3 4]


In [37]:
arr=np.array(lst,ndmin=2)

In [38]:
arr

array([[1, 2, 3, 4]])

# 2)Arrange Function

In [39]:
np.arange(1,10,5)

array([1, 6])

In [40]:
for i in range(1,10,1):
    print(i)

1
2
3
4
5
6
7
8
9


In [41]:
for i in range(1,10,2):
    print(i)

1
3
5
7
9


# 3)Multidimentional Array

In [42]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

print("Total :",arr.size)
print("Rows :",np.size(arr,0))
print("Cols :",np.size(arr,1))
arr

Total : 9
Rows : 3
Cols : 3


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# 4)Shape Function

In [43]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print((np.size(arr,1),np.size(arr,0)))
print(arr.shape)

(3, 3)
(3, 3)


# 5)Dtype Function

In [44]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1=np.array([[1.5,2.5,3.5],[4.5,5.5,6.5],[7.5,8.5,9.5]])
print(arr.dtype)
print(arr1.dtype)

int32
float64


# 6)Ndim Fucntion

In [45]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([1,2,3,4,5,6,7,8,9])
print(arr1.ndim)
print(arr2.ndim)


arr3=np.array(arr1,ndmin=3)
print(arr3)

2
1
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


# 7)Zeros FUnction

In [46]:
arr=np.zeros(shape=(3,5),dtype=int)
print(arr)


[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


# 8)Ones Function

In [47]:
arr=np.ones(shape=(3,5),dtype=int)
print(arr)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


# 9)Eye Function

In [48]:
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

# 10)Empty Function

In [49]:
np.empty(shape=(5,5))

array([[8.00133728e-312, 7.60861095e-322, 0.00000000e+000,
        0.00000000e+000, 8.90104238e-307],
       [1.15998412e-028, 4.31603868e-080, 1.94919985e-153,
        1.35717430e+131, 6.98346901e-077],
       [1.81148490e-152, 9.37041222e-076, 1.05117820e-153,
        6.01391519e-154, 1.05121175e-153],
       [7.68132025e+140, 6.01347002e-154, 7.54951879e-096,
        1.95360725e-109, 4.90900643e+252],
       [1.94918511e-153, 6.32672800e+180, 4.74483502e+170,
        4.59210323e-072, 3.22136532e-317]])

# 11)Random Function

a)np.random.rand

In [50]:
np.random.rand(3,4)

array([[0.34556073, 0.39676747, 0.53881673, 0.41919451],
       [0.6852195 , 0.20445225, 0.87811744, 0.02738759],
       [0.67046751, 0.4173048 , 0.55868983, 0.14038694]])

b)np.random.randint

In [51]:
np.random.randint(low=1,high=10,size=10)

array([1, 7, 8, 7, 2, 1, 2, 9, 9, 4])

c)np.random.randn

In [52]:
np.random.randn(10)

array([-0.17242821, -0.87785842,  0.04221375,  0.58281521, -1.10061918,
        1.14472371,  0.90159072,  0.50249434,  0.90085595, -0.68372786])

# 12)Reshape Function

In [53]:
arr=np.random.randint(1,15,(3,4))
print(arr)

[[11 10  9  7]
 [10  4  8  8]
 [14  5 12  6]]


In [54]:
arr=arr.reshape(4,3)
print(arr)

[[11 10  9]
 [ 7 10  4]
 [ 8  8 14]
 [ 5 12  6]]


# 13)Linspace Function

In [55]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

# 14)Flatten Function

In [56]:
arr=np.random.randint(1,15,(3,4))
print(arr)

arr=arr.flatten()
print(arr)

[[10  4  7  9]
 [ 1  3 11  8]
 [ 8 10  8  4]]
[10  4  7  9  1  3 11  8  8 10  8  4]


# 15)Logspace Fucntion

In [57]:
print(np.logspace(2,15,5))
print(np.logspace(3,21,8 ,base=2))      

[1.00000000e+02 1.77827941e+05 3.16227766e+08 5.62341325e+11
 1.00000000e+15]
[8.00000000e+00 4.75518173e+01 2.82646916e+02 1.68004681e+03
 9.98615986e+03 5.93575061e+04 3.52819660e+05 2.09715200e+06]


# 16)Copy Function

In [58]:
arr1=np.random.randint(1,15,(3,4))
arr1=arr2
print(arr1,id(arr1))
print(arr2,id(arr2))

[1 2 3 4 5 6 7 8 9] 1619581067568
[1 2 3 4 5 6 7 8 9] 1619581067568


# 17)arr.min(),arr.max(),arr.sum() Functions

In [59]:
arr=np.random.randint(1,15,(3,4))
print(arr)
print("Min :",arr.min())
print("Max",arr.max())
print("Sum",arr.sum())

[[14 14  7  5]
 [ 6  7  3 13]
 [12  6 12  8]]
Min : 3
Max 14
Sum 107


In [60]:
#For cols
print("Min :",arr.min(axis=0))
print("Max",arr.max(axis=0))
print("Sum",arr.sum(axis=0))

Min : [6 6 3 5]
Max [14 14 12 13]
Sum [32 27 22 26]


In [61]:
#For Rows
print("Min :",arr.min(axis=1))
print("Max",arr.max(axis=1))
print("Sum",arr.sum(axis=1))

Min : [5 3 6]
Max [14 13 12]
Sum [40 29 38]


# 18)Seed Fucntion

In [62]:
np.random.seed(1)
arr=np.random.randint(1,15,(3,4))
print(arr)

[[ 6 12 13  9]
 [10 12  6  1]
 [ 1  2 13  8]]


# 18)Sorting Function

In [63]:
np.random.seed(1)
arr=np.random.randint(1,15,(3,4))
print(arr)
print("-"*15)

print(np.sort(arr,axis=1))
print("-"*15)
print(np.sort(arr,axis=0))
print("-"*15)

np.sort(arr.flatten())
print("-"*15)

arr=np.reshape(np.sort(arr.flatten()),arr.shape)
print(arr)


[[ 6 12 13  9]
 [10 12  6  1]
 [ 1  2 13  8]]
---------------
[[ 6  9 12 13]
 [ 1  6 10 12]
 [ 1  2  8 13]]
---------------
[[ 1  2  6  1]
 [ 6 12 13  8]
 [10 12 13  9]]
---------------
---------------
[[ 1  1  2  6]
 [ 6  8  9 10]
 [12 12 13 13]]


In [64]:

print(np.sort(arr,axis=1,kind="mergsort"))

[[ 1  1  2  6]
 [ 6  8  9 10]
 [12 12 13 13]]


# 19)Mathamatical OIperations

a)Adding

In [65]:
np.random.seed(1)
arr=np.random.randint(1,15,(3,4))
print(arr)
print("-"*15)

arr1=arr+1
print(arr1)

[[ 6 12 13  9]
 [10 12  6  1]
 [ 1  2 13  8]]
---------------
[[ 7 13 14 10]
 [11 13  7  2]
 [ 2  3 14  9]]


b)Substraction

In [66]:
np.random.seed(1)
arr=np.random.randint(1,15,(3,4))
print(arr)
print("-"*15)

arr1=arr-2
print(arr1)

[[ 6 12 13  9]
 [10 12  6  1]
 [ 1  2 13  8]]
---------------
[[ 4 10 11  7]
 [ 8 10  4 -1]
 [-1  0 11  6]]


c)Multiplication

In [67]:
np.random.seed(1)
arr=np.random.randint(1,15,(3,4))
print(arr)
print("-"*15)

arr1=arr*2
print(arr1)

[[ 6 12 13  9]
 [10 12  6  1]
 [ 1  2 13  8]]
---------------
[[12 24 26 18]
 [20 24 12  2]
 [ 2  4 26 16]]


d)Division

In [68]:
np.random.seed(1)
arr=np.random.randint(1,15,(3,4))
print(arr)
print("-"*15)

arr1=arr/2
print(arr1)
print("-"*15)

arr2=arr//2
print(arr2)

[[ 6 12 13  9]
 [10 12  6  1]
 [ 1  2 13  8]]
---------------
[[3.  6.  6.5 4.5]
 [5.  6.  3.  0.5]
 [0.5 1.  6.5 4. ]]
---------------
[[3 6 6 4]
 [5 6 3 0]
 [0 1 6 4]]


e)Matrix Multiplication

In [74]:
np.random.seed(3)
arr1=np.random.randint(1,10,(2,2))
arr2=np.random.randint(1,10,(2,2))
arr1


array([[9, 4],
       [9, 9]])

In [75]:
arr2

array([[1, 6],
       [4, 6]])

In [76]:
arr1.dot(arr2)

array([[ 25,  78],
       [ 45, 108]])

In [77]:
arr2.dot(arr1)

array([[63, 58],
       [90, 70]])

f)Power Operation 

In [78]:
print(arr2)
print("-"*15)
print(arr2**2)

[[1 6]
 [4 6]]
---------------
[[ 1 36]
 [16 36]]


# 20)Percentile Function

In [85]:
np.random.seed(3)
arr=np.random.randint(1,10,10)
print(arr)
print("-"*15)

arr=np.sort(arr)
print(arr)

print(np.percentile(arr,75))

[9 4 9 9 1 6 4 6 8 7]
---------------
[1 4 4 6 6 7 8 9 9 9]
8.75


# 21) Mean, Variance and Standard Deviation

In [88]:
np.random.seed(3)
arr=np.random.randint(1,10,10)
print(arr)

print("Mean :",arr.mean())
print("Variance :",arr.var())
print("Standard Deviation :",arr.std())


[9 4 9 9 1 6 4 6 8 7]
Mean : 6.3
Variance : 6.410000000000001
Standard Deviation : 2.5317977802344327


# 22)Filter Function

In [90]:
arr=np.arange(1,15)
print(arr)
print(arr<5)
print(arr[arr<5])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ True  True  True  True False False False False False False False False
 False False]
[1 2 3 4]


In [95]:
arr [arr> 5]=10

In [96]:
arr

array([10, 10, 10, 10,  5, 10, 10, 10, 10, 10, 10, 10, 10, 10])

# 23)Transposing Array

In [98]:
arr=np.random.randint(1,20,(3,5))
print(arr)
print("-"*20)
print(arr.T)

[[ 2 16 17  6 18]
 [15  1  1 10 19]
 [ 6  8  6 15  2]]
--------------------
[[ 2 15  6]
 [16  1  8]
 [17  1  6]
 [ 6 10 15]
 [18 19  2]]


# 24)Where Function

In [104]:
arr=np.random.randint(1,100,10)
print(arr)

[56 97 96 14 38 31 49 62 34 53]


In [109]:
print(np.where(arr%2==0,"even",arr))
print(np.where(arr%2!=0,"odd",arr))

['even' '97' 'even' 'even' 'even' '31' '49' 'even' 'even' '53']
['56' 'odd' '96' '14' '38' 'odd' 'odd' '62' '34' 'odd']


In [101]:
arr

(array([0, 1, 3, 9], dtype=int64),)

# 25)Merging Array

In [110]:
arr1=np.random.randint(1,10,(2,4))
arr2=np.random.randint(1,10,(2,4))
arr1,arr2

(array([[2, 3, 3, 5],
        [9, 1, 7, 1]]),
 array([[5, 2, 6, 2],
        [9, 9, 8, 1]]))

In [114]:
np.concatenate((arr1,arr2), axis=0)

array([[2, 3, 3, 5],
       [9, 1, 7, 1],
       [5, 2, 6, 2],
       [9, 9, 8, 1]])

In [115]:
np.concatenate((arr1,arr2), axis=1)

array([[2, 3, 3, 5, 5, 2, 6, 2],
       [9, 1, 7, 1, 9, 9, 8, 1]])

# 26)Spliting Array

In [120]:
arr=np.random.randint(1,10,(4,4))
print(arr)

[[4 3 5 2]
 [3 3 8 4]
 [5 2 7 8]
 [2 1 1 6]]


In [121]:
np.vsplit(arr,2)

[array([[4, 3, 5, 2],
        [3, 3, 8, 4]]),
 array([[5, 2, 7, 8],
        [2, 1, 1, 6]])]

In [122]:
np.hsplit(arr,2)

[array([[4, 3],
        [3, 3],
        [5, 2],
        [2, 1]]),
 array([[5, 2],
        [8, 4],
        [7, 8],
        [1, 6]])]